# Generated by Django 6.0.4 on 2026-04-20 03:41

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='not_known', max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('recovery_question', models.CharField(blank=True, choices=[('pet_name', 'What is your pet name?'), ('first_school', 'What is your first school name?'), ('hobby', 'What is your favorite hobby?')], max_length=50)),
                ('recovery_answer', models.CharField(blank=True, max_length=255)),
                ('profile_avatar', models.ImageField(blank=True, default='users/profiles/avatar1.jpg', upload_to='users/profiles')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('address_line', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField()),
                ('disease_key', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('asthma', 'Asthma'), ('heart_disease', 'Heart Disease'), ('arthritis', 'Arthritis'), ('chronic_kidney_disease', 'Chronic Kidney Disease'), ('copd', 'COPD'), ('thyroid_disorder', 'Thyroid Disorder'), ('epilepsy', 'Epilepsy'), ('allergy', 'Allergy'), ('tuberculosis', 'Tuberculosis'), ('migraine', 'Migraine'), ('cancer', 'Cancer'), ('other', 'Other')], default='other', max_length=30)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialty',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('previous_disease', models.CharField(choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('asthma', 'Asthma'), ('heart_disease', 'Heart Disease'), ('arthritis', 'Arthritis'), ('chronic_kidney_disease', 'Chronic Kidney Disease'), ('copd', 'COPD'), ('thyroid_disorder', 'Thyroid Disorder'), ('epilepsy', 'Epilepsy'), ('allergy', 'Allergy'), ('tuberculosis', 'Tuberculosis'), ('migraine', 'Migraine'), ('cancer', 'Cancer'), ('other', 'Other')], default='none', max_length=30)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='id_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specialty')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
