# Generated by Django 6.0.4 on 2026-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='recovery_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='recovery_question',
            field=models.CharField(blank=True, choices=[('pet_name', 'What is your pet name?'), ('first_school', 'What is your first school name?'), ('hobby', 'What is your favorite hobby?')], max_length=50),
        ),
    ]
