# Generated by Django 6.0.4 on 2026-05-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='disease_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='diseases', to='users.specialty')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.AddField(
            model_name='patients',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='patients', to='users.disease'),
        ),
    ]
