# Generated by Django 6.0.4 on 2026-05-10 15:09

from django.db import migrations


def drop_insurance_if_exists(apps, schema_editor):
    Patients = apps.get_model('users', 'Patients')
    table_name = Patients._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'insurance' in columns:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} "
            f"DROP COLUMN {schema_editor.quote_name('insurance')}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_specialty_disease_key_disease_patients_diseases'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_insurance_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='patients',
                    name='insurance',
                ),
            ],
        ),
    ]
