# Generated by Django 6.0.4 on 2026-04-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_users_recovery_answer_users_recovery_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reste_token',
        ),
    ]
